apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  creationTimestamp: null
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx 
        image: nginx:latest
        ports:
        - containerPort: 80
        resources: 
          limits:
            memory: "32Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always

