---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap-test
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type text/plain;

        location / {
            return 200 '$hostname\n latest version for testing';
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-test
  name: web-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - image: nginx:1.20.2
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-nginx-test
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-nginx-test
          configMap:
            name: nginx-configmap-test

---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: web-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: web-test

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: canary
    nginx.ingress.kubernetes.io/canary-weight: "25"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: test
             port:
                number: 80